FROM node:latest
ADD . /app
WORKDIR /app

ARG API_EMAIL
ARG API_KEY
ARG API_PRIVATE_KEY
ARG API_PUBLIC_KEY
ARG API_SHORT_NAME
ARG AWS_ACCESS_KEY_ID
ARG AWS_REGION
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_BUCKET_NAME
ARG CLIENT_INVITE_SOURCE_ADDRESS
ARG DB_HOST
ARG DB_PORT
ARG DB_POSTGRES_DB
ARG DB_POSTGRES_PASSWORD
ARG DB_POSTGRES_USER
ARG LINKEDIN_BASE_AUTH_URL
ARG LINKEDIN_BASE_URL
ARG LINKEDIN_CLIENT_ID
ARG LINKEDIN_CLIENT_SECRET
ARG LINKEDIN_REDIRECT_URL
ARG NODE_PORT
ARG REDIS_HOST
ARG REDIS_PASSWORD
ARG REDIS_PORT
ARG SLACK_APP_ID
ARG SLACK_BASE_AUTH_URL
ARG SLACK_BASE_URL
ARG SLACK_CLIENT_ID
ARG SLACK_CLIENT_SECRET
ARG SLACK_REDIRECT_URL
ARG SLACK_SIGNING_SECRET
ARG UI_URL
ARG useSSL
ARG NODE_ENV
ARG PORT

ENV API_EMAIL=${API_EMAIL}
ENV API_KEY=${API_KEY}
ENV API_PRIVATE_KEY=${API_PRIVATE_KEY}
ENV API_PUBLIC_KEY=${API_PUBLIC_KEY}
ENV API_SHORT_NAME=${API_SHORT_NAME}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_REGION=${AWS_REGION}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
ENV CLIENT_INVITE_SOURCE_ADDRESS=${CLIENT_INVITE_SOURCE_ADDRESS}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_POSTGRES_DB=${DB_POSTGRES_DB}
ENV DB_POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
ENV DB_POSTGRES_USER=${DB_POSTGRES_USER}
ENV LINKEDIN_BASE_AUTH_URL=${LINKEDIN_BASE_AUTH_URL}
ENV LINKEDIN_BASE_URL=${LINKEDIN_BASE_URL}
ENV LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
ENV LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
ENV LINKEDIN_REDIRECT_URL=${LINKEDIN_REDIRECT_URL}
ENV NODE_PORT=${NODE_PORT}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_PORT=${REDIS_PORT}
ENV SLACK_APP_ID=${SLACK_APP_ID}
ENV SLACK_BASE_AUTH_URL=${SLACK_BASE_AUTH_URL}
ENV SLACK_BASE_URL=${SLACK_BASE_URL}
ENV SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
ENV SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
ENV SLACK_REDIRECT_URL=${SLACK_REDIRECT_URL}
ENV SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
ENV UI_URL=${UI_URL}
ENV useSSL=${useSSL}
ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}

COPY . /usr/src/app
RUN ls && more package.json 
RUN yarn global add typescript && \
    yarn install --production --silent && \
    yarn build && \
    ls

EXPOSE 5000
ENTRYPOINT ["/bin/bash", "-c", "./entrypoint.sh"]
